// examples/react-starter/src/main.tsx
import { RuntimeProvider, createEffectRuntime } from "@effect-ui/react";
import { hydrateFromDocument } from "@effect-ui/start";
import { Data, Layer } from "effect";
import { createRoot, hydrateRoot } from "react-dom/client";
import App from "./App.js";

class ReactStarterRootMissing extends Data.TaggedError("ReactStarterRootMissing")<{
  readonly id: string;
  readonly guidance: string;
}> {}

const root = document.getElementById("root");

if (!root) {
  throw new ReactStarterRootMissing({
    id: "root",
    guidance: "Add a root element with id=\"root\" to the document shell."
  });
}

const runtime = createEffectRuntime(Layer.empty);
hydrateFromDocument(document, undefined, { runtime });

const Root = () => (
  <RuntimeProvider runtime={runtime}>
    <App />
  </RuntimeProvider>
);

if (root.hasChildNodes()) {
  hydrateRoot(root, <Root />);
} else {
  createRoot(root).render(<Root />);
}

// examples/basic-starter/src/main.tsx
import { RuntimeProvider, createEffectRuntime } from "@effect-ui/solid";
import { hydrateFromDocument } from "@effect-ui/start";
import { Data, Layer } from "effect";
import { hydrate, render } from "solid-js/web";
import App from "./App.js";

class StarterRootMissing extends Data.TaggedError("StarterRootMissing")<{
  readonly id: string;
  readonly guidance: string;
}> {}

const root = document.getElementById("root");

if (!root) {
  throw new StarterRootMissing({
    id: "root",
    guidance: 'Add a root element with id="root" to the document shell.',
  });
}

const runtime = createEffectRuntime(Layer.empty);
hydrateFromDocument(document, undefined, { runtime });

const Root = () => (
  <RuntimeProvider runtime={runtime}>
    <App />
  </RuntimeProvider>
);

if (root.hasChildNodes()) {
  hydrate(Root, root);
} else {
  render(Root, root);
}
