// examples/react-starter/src/main.tsx
import { RuntimeProvider, createEffectRuntime } from "@sunfall/arc-react";
import { hydrateFromDocument } from "@sunfall/arc-start";
import { Data, Layer } from "effect";
import { createRoot, hydrateRoot } from "react-dom/client";
import App from "./App.js";

class ReactStarterRootMissing extends Data.TaggedError("ReactStarterRootMissing")<{
  readonly id: string;
  readonly guidance: string;
}> {}

const root = document.getElementById("root");

if (!root) {
  throw new ReactStarterRootMissing({
    id: "root",
    guidance: 'Add a root element with id="root" to the document shell.',
  });
}

const runtime = createEffectRuntime(Layer.empty);
hydrateFromDocument(document, undefined, { runtime });

const Root = () => (
  <RuntimeProvider runtime={runtime}>
    <App hydrating={root.hasChildNodes()} />
  </RuntimeProvider>
);

if (root.hasChildNodes()) {
  hydrateRoot(root, <Root />);
} else {
  createRoot(root).render(<Root />);
}

// examples/docs-site/src/main.tsx
import { RuntimeProvider, createEffectRuntime } from "@sunfall/arc-solid";
import { BrowserRpcLive, hydrateFromDocument } from "@sunfall/arc-start";
import { Data, Layer } from "effect";
import { hydrate, render } from "solid-js/web";
import App from "./App.js";
import { DocsContentApiLive } from "./content.js";

class DocsSiteRootMissing extends Data.TaggedError("DocsSiteRootMissing")<{
  readonly id: string;
  readonly guidance: string;
}> {}

const root = document.getElementById("root");

if (!root) {
  throw new DocsSiteRootMissing({
    id: "root",
    guidance: 'Add a root element with id="root" to the document shell.',
  });
}

const runtime = createEffectRuntime(Layer.mergeAll(BrowserRpcLive, DocsContentApiLive));
hydrateFromDocument(document, undefined, { runtime });

const Root = () => (
  <RuntimeProvider runtime={runtime}>
    <App runtime={runtime} />
  </RuntimeProvider>
);

if (root.hasChildNodes()) {
  hydrate(Root, root);
} else {
  render(Root, root);
}
