// packages/solid/src/route-render-scope.ts
import {
  makeRuntimeUiScope,
  runWithRuntime,
  runWithScope,
  type AnyEffectUiRuntime,
  type BrowserRouterState,
  type Route
} from "@effect-ui/core";
import { Effect, Fiber } from "effect";
import {
  createRoot,
  type Component,
  type JSX,
  type Setter
} from "solid-js";
import { createComponent } from "solid-js/web";

type AnyRoute = Route.Definition<string, unknown, unknown, any>;

export type SolidRouteOutletRenderers<Routes extends readonly AnyRoute[], ER> = {
  readonly pending?: (state: Extract<BrowserRouterState<Routes, ER>, { readonly _tag: "Pending" }>) => JSX.Element;
  readonly failure?: (state: Extract<BrowserRouterState<Routes, ER>, { readonly _tag: "Failure" }>) => JSX.Element;
  readonly notFound?: (state: Extract<BrowserRouterState<Routes, ER>, { readonly _tag: "NotFound" }>) => JSX.Element;
};

export interface SolidRouteRenderScopeController<Routes extends readonly AnyRoute[], ER> {
  update(state: BrowserRouterState<Routes, ER>): void;
  dispose(): void;
}

interface RenderedRouteScope {
  readonly node: JSX.Element;
  readonly dispose?: Effect.Effect<void, never, never>;
}

const defaultPending = (): JSX.Element => undefined;

const defaultFailure = <ER>(
  state: Extract<BrowserRouterState<readonly AnyRoute[], ER>, { readonly _tag: "Failure" }>
): JSX.Element => {
  throw state.cause;
};

const defaultNotFound = (): JSX.Element => undefined;

const renderInRouteScope = <ER>(
  runtime: AnyEffectUiRuntime<ER>,
  render: () => JSX.Element
): { readonly node: JSX.Element; readonly dispose: Effect.Effect<void, never, never> } => {
  const routeScope = makeRuntimeUiScope(runtime);
  let disposeSolid: (() => void) | undefined;
  const node = createRoot((disposeRoot) => {
    disposeSolid = disposeRoot;
    return runWithRuntime(runtime, () =>
      runWithScope(routeScope, render)
    );
  });
  const dispose = Effect.andThen(
    Effect.sync(() => {
      runWithRuntime(runtime, () =>
        runWithScope(routeScope, () => {
          disposeSolid?.();
        })
      );
    }),
    runtime.provide(routeScope.disposeEffect()).pipe(Effect.catchCause(() => Effect.void))
  ).pipe(Effect.catchCause(() => Effect.void));

  return { node, dispose };
};

const renderRouteState = <Routes extends readonly AnyRoute[], ER>(
  state: BrowserRouterState<Routes, ER>,
  renderers: SolidRouteOutletRenderers<Routes, ER>,
  runtime: AnyEffectUiRuntime<ER>
): RenderedRouteScope => {
  switch (state._tag) {
    case "Pending":
      return renderInRouteScope(runtime, () => (renderers.pending ?? defaultPending)(state));
    case "Failure":
      return renderInRouteScope(runtime, () => (renderers.failure ?? defaultFailure)(state));
    case "NotFound":
      return renderInRouteScope(runtime, () => (renderers.notFound ?? defaultNotFound)(state));
    case "Ready": {
      const component = state.match.route.options.component as Component<Record<string, unknown>> | undefined;
      if (!component) {
        return { node: undefined };
      }

      return renderInRouteScope(runtime, () =>
        createComponent(component, {
          params: state.match.params,
          search: state.match.search,
          match: state.match
        })
      );
    }
  }
};

const disposeRenderedRoute = (
  dispose: Effect.Effect<void, never, never> | undefined
): Effect.Effect<void> =>
  dispose ?? Effect.void;

export const makeSolidRouteRenderScopeController = <Routes extends readonly AnyRoute[], ER>(options: {
  readonly initialState: BrowserRouterState<Routes, ER>;
  readonly renderers: SolidRouteOutletRenderers<Routes, ER>;
  readonly runtime: AnyEffectUiRuntime<ER>;
  readonly setNode: Setter<JSX.Element>;
}): SolidRouteRenderScopeController<Routes, ER> => {
  let renderedState = options.initialState;
  const initial = renderRouteState(renderedState, options.renderers, options.runtime);
  options.setNode(() => initial.node);
  let disposeRoute: Effect.Effect<void, never, never> | undefined = initial.dispose;
  let transitionVersion = 0;
  let disposalFiber: Fiber.Fiber<void, unknown> | undefined;

  const disposeCurrentRoute = (): void => {
    const previousDisposalFiber = disposalFiber;
    const currentDisposal = disposeRenderedRoute(disposeRoute);
    disposeRoute = undefined;
    disposalFiber = options.runtime.runFork(
      Effect.gen(function* () {
        if (previousDisposalFiber !== undefined) {
          yield* Fiber.join(previousDisposalFiber);
        }
        yield* currentDisposal;
      }).pipe(Effect.catchCause(() => Effect.void))
    );
  };

  return {
    update: (state) => {
      if (state === renderedState) {
        return;
      }

      renderedState = state;
      const transition = ++transitionVersion;
      options.setNode(() => undefined);
      disposeCurrentRoute();
      const transitionDisposalFiber = disposalFiber;
      void options.runtime.runFork(
        Effect.gen(function* () {
          if (transitionDisposalFiber !== undefined) {
            yield* Fiber.join(transitionDisposalFiber);
          }
          if (transition !== transitionVersion) {
            return;
          }

          const next = renderRouteState(state, options.renderers, options.runtime);
          options.setNode(() => next.node);
          disposeRoute = next.dispose;
        })
      );
    },
    dispose: () => {
      transitionVersion++;
      disposeCurrentRoute();
    }
  };
};

// packages/react/src/route-render-scope.ts
import {
  makeRuntimeUiScope,
  runWithRuntime,
  runWithScope,
  type AnyEffectUiRuntime,
  type BrowserRouterState,
  type Route,
  type UiScope
} from "@effect-ui/core";
import { Effect } from "effect";
import {
  createElement,
  useEffect,
  useRef,
  type ReactNode
} from "react";
import { RuntimeContext } from "./runtime.js";

type AnyRoute = Route.Definition<string, unknown, unknown, any>;

export type ReactRouteOutletRenderers<Routes extends readonly AnyRoute[], ER> = {
  readonly pending?: (state: Extract<BrowserRouterState<Routes, ER>, { readonly _tag: "Pending" }>) => ReactNode;
  readonly failure?: (state: Extract<BrowserRouterState<Routes, ER>, { readonly _tag: "Failure" }>) => ReactNode;
  readonly notFound?: (state: Extract<BrowserRouterState<Routes, ER>, { readonly _tag: "NotFound" }>) => ReactNode;
};

const defaultPending = (): ReactNode => undefined;

const defaultFailure = <ER>(
  routeState: Extract<BrowserRouterState<readonly AnyRoute[], ER>, { readonly _tag: "Failure" }>
): ReactNode => {
  throw routeState.cause;
};

const defaultNotFound = (): ReactNode => undefined;

interface RouteRenderFrameProps<ER> {
  readonly runtime: AnyEffectUiRuntime<ER>;
  readonly render: () => ReactNode;
}

const RouteRenderFrame = <ER,>(props: RouteRenderFrameProps<ER>): ReactNode => {
  const scopeRef = useRef<{
    readonly runtime: AnyEffectUiRuntime<ER>;
    readonly scope: UiScope;
  } | undefined>(undefined);

  if (scopeRef.current === undefined || scopeRef.current.runtime !== props.runtime) {
    scopeRef.current = {
      runtime: props.runtime,
      scope: makeRuntimeUiScope(props.runtime)
    };
  }

  const scope = scopeRef.current.scope;

  useEffect(() => {
    return () => {
      void props.runtime.runFork(
        props.runtime.provide(scope.disposeEffect()).pipe(
          Effect.catch(() => Effect.void)
        )
      );
    };
  }, [props.runtime, scope]);

  return runWithRuntime(props.runtime, () =>
    runWithScope(scope, props.render)
  );
};

const routeRenderKey = <Routes extends readonly AnyRoute[], ER>(
  routeState: BrowserRouterState<Routes, ER>
): string => {
  switch (routeState._tag) {
    case "Pending":
    case "Ready":
      return `${routeState._tag}:${routeState.href}:${routeState.match.route.path}`;
    case "Failure":
      return routeState.match
        ? `${routeState._tag}:${routeState.href}:${routeState.match.route.path}`
        : `${routeState._tag}:${routeState.href}`;
    case "NotFound":
      return `${routeState._tag}:${routeState.href}`;
  }
};

const renderInRouteScope = <Routes extends readonly AnyRoute[], ER>(
  runtime: AnyEffectUiRuntime<ER>,
  routeState: BrowserRouterState<Routes, ER>,
  render: () => ReactNode
): ReactNode =>
  createElement(RuntimeContext.Provider, {
    value: runtime as AnyEffectUiRuntime<never>,
    children: createElement(RouteRenderFrame, {
      key: routeRenderKey(routeState),
      runtime,
      render
    })
  });

export const renderReactRouteState = <Routes extends readonly AnyRoute[], ER>(
  routeState: BrowserRouterState<Routes, ER>,
  renderers: ReactRouteOutletRenderers<Routes, ER>,
  runtime: AnyEffectUiRuntime<ER>
): ReactNode => {
  switch (routeState._tag) {
    case "Pending":
      return renderInRouteScope(runtime, routeState, () =>
        (renderers.pending ?? defaultPending)(routeState)
      );
    case "Failure":
      return renderInRouteScope(runtime, routeState, () =>
        (renderers.failure ?? defaultFailure)(routeState)
      );
    case "NotFound":
      return renderInRouteScope(runtime, routeState, () =>
        (renderers.notFound ?? defaultNotFound)(routeState)
      );
    case "Ready": {
      const component = routeState.match.route.options.component as
        | ((props: Record<string, unknown>) => ReactNode)
        | undefined;
      if (!component) {
        return undefined;
      }

      return renderInRouteScope(runtime, routeState, () =>
        component({
          params: routeState.match.params,
          search: routeState.match.search,
          match: routeState.match
        })
      );
    }
  }
};
