// packages/solid/src/runtime.ts
import {
  currentOrDefaultRuntime,
  invokeEffectInput,
  makeRuntimeUiScopeFrame,
  makeRuntime,
  runWithRuntime,
  type AnyEffectUiRuntime,
  type EffectInput,
  type EffectUiRuntime,
  type RuntimeDisposeError,
  type UiScope
} from "@effect-ui/core";
import { Effect, Layer, ManagedRuntime } from "effect";
import { createContext, createMemo, createRenderEffect, createRoot, createSignal, onCleanup, useContext, type JSX } from "solid-js";
import { createComponent } from "solid-js/web";

/** Solid context carrying the active Effect UI Runtime Spine. */
export const RuntimeContext = createContext<AnyEffectUiRuntime<never>>();

/** Props for providing an Effect UI runtime to Solid descendants. */
interface RuntimeProviderChildren {
  readonly children?: JSX.Element;
}

interface RuntimeProviderRuntimeProps<RuntimeServices = never, ER = never> extends RuntimeProviderChildren {
  /** Existing host-owned runtime. The provider exposes it and does not dispose it. */
  readonly runtime: EffectUiRuntime<RuntimeServices, ER> | AnyEffectUiRuntime<ER>;
  readonly source?: never;
  readonly onDisposeFailure?: never;
}

interface RuntimeProviderSourceProps<RuntimeServices = never, ER = never> extends RuntimeProviderChildren {
  readonly runtime?: never;
  /** Runtime source owned by this Solid provider and disposed with its owner. */
  readonly source: ManagedRuntime.ManagedRuntime<RuntimeServices, ER> | Layer.Layer<RuntimeServices, ER, never>;
  /**
   * Observes failures from provider-owned runtime disposal.
   *
   * Promise-shaped observers are rejected by `EffectInput`; observer failures
   * are ignored after the disposal failure has been reported.
   */
  readonly onDisposeFailure?: (error: RuntimeDisposeError) => EffectInput<void, unknown>;
}

interface RuntimeProviderDefaultProps extends RuntimeProviderChildren {
  readonly runtime?: undefined;
  readonly source?: undefined;
  /**
   * Observes failures from provider-owned runtime disposal.
   *
   * Promise-shaped observers are rejected by `EffectInput`; observer failures
   * are ignored after the disposal failure has been reported.
   */
  readonly onDisposeFailure?: (error: RuntimeDisposeError) => EffectInput<void, unknown>;
}

/** Props accepted by Solid `RuntimeProvider` for host-owned or provider-owned runtimes. */
export type RuntimeProviderProps<RuntimeServices = never, ER = never> =
  | RuntimeProviderRuntimeProps<RuntimeServices, ER>
  | RuntimeProviderSourceProps<RuntimeServices, ER>
  | RuntimeProviderDefaultProps;

interface RuntimeProviderEntry<ER> {
  readonly runtime: AnyEffectUiRuntime<ER>;
  readonly ownsRuntime: boolean;
}

/** Creates an Effect UI runtime for Solid applications. */
export const createEffectRuntime = makeRuntime;

/** Reads the nearest Solid runtime context, falling back to the current/default runtime. */
export const useRuntime = <ER = never>(): AnyEffectUiRuntime<ER> =>
  (useContext(RuntimeContext) ?? currentOrDefaultRuntime()) as AnyEffectUiRuntime<ER>;

/**
 * Provides an Effect UI runtime to Solid children.
 *
 * Pass an existing runtime when the host owns lifecycle. Pass a runtime source
 * to let the provider create and dispose a runtime with the Solid owner.
 */
export const RuntimeProvider = <RuntimeServices = never, ER = never>(
  props: RuntimeProviderProps<RuntimeServices, ER>
): JSX.Element => {
  const entry = createMemo<RuntimeProviderEntry<ER>>(() => ({
    runtime: (props.runtime ?? makeRuntime(props.source)) as AnyEffectUiRuntime<ER>,
    ownsRuntime: props.runtime === undefined
  }));
  const [view, setView] = createSignal<JSX.Element>();
  let disposeEntry: (() => void) | undefined;

  const mountEntry = (current: RuntimeProviderEntry<ER>): void => {
    disposeEntry?.();
    createRoot((dispose) => {
      disposeEntry = dispose;
      const next = createComponent(RuntimeProviderInstance, {
        entry: current,
        get onDisposeFailure() {
          return props.onDisposeFailure;
        },
        get children() {
          return props.children;
        }
      });
      setView(() => next);
    });
  };

  let mountedEntry = entry();
  mountEntry(mountedEntry);
  createRenderEffect(() => {
    const current = entry();
    if (current === mountedEntry) {
      return;
    }
    mountedEntry = current;
    mountEntry(current);
  });
  onCleanup(() => disposeEntry?.());

  return view as unknown as JSX.Element;
};

const RuntimeProviderInstance = <ER>(
  props: {
    readonly entry: RuntimeProviderEntry<ER>;
    readonly onDisposeFailure?: ((error: RuntimeDisposeError) => EffectInput<void, unknown>) | undefined;
    readonly children?: JSX.Element;
  }
): JSX.Element => {
  if (props.entry.ownsRuntime) {
    onCleanup(() => {
      void Effect.runFork(
        props.entry.runtime.disposeEffect.pipe(
          Effect.catch((error) =>
            props.onDisposeFailure === undefined
              ? Effect.void
              : invokeEffectInput("SolidRuntimeProvider.onDisposeFailure", props.onDisposeFailure, error).pipe(
                  Effect.catchCause(() => Effect.void),
                  Effect.asVoid
                )
          )
        )
      );
    });
  }

  return createComponent(RuntimeContext.Provider, {
    value: props.entry.runtime as unknown as AnyEffectUiRuntime<never>,
    get children() {
      return runWithRuntime(props.entry.runtime, () => props.children);
    }
  });
};

/** Creates a `UiScope` bound to the current Solid owner cleanup. */
export const createComponentScope = <A>(f: (scope: UiScope) => A): A => {
  const runtime = useRuntime();
  const frame = makeRuntimeUiScopeFrame(runtime);
  onCleanup(() => {
    void runtime.runFork(frame.disposeEffect());
  });
  return frame.run(() => f(frame.scope));
};

// packages/react/src/runtime.ts
import {
  currentOrDefaultRuntime,
  invokeEffectInput,
  makeRuntimeUiScopeFrame,
  makeRuntime,
  runWithScope,
  runWithRuntime,
  type AnyEffectUiRuntime,
  type EffectInput,
  type EffectUiRuntime,
  type RuntimeDisposeError,
  type RuntimeUiScopeFrame,
  type UiScope
} from "@effect-ui/core";
import { Effect, Layer, ManagedRuntime } from "effect";
import {
  createContext,
  createElement,
  useContext,
  useEffect,
  useRef,
  type ReactNode
} from "react";

/** React context carrying the active Effect UI Runtime Spine. */
export const RuntimeContext = createContext<AnyEffectUiRuntime<never> | undefined>(undefined);

/** Props for providing an Effect UI runtime to React descendants. */
interface RuntimeProviderChildren {
  readonly children?: ReactNode;
}

interface RuntimeProviderRuntimeProps<RuntimeServices = never, ER = never> extends RuntimeProviderChildren {
  /** Existing host-owned runtime. The provider exposes it and does not dispose it. */
  readonly runtime: EffectUiRuntime<RuntimeServices, ER> | AnyEffectUiRuntime<ER>;
  readonly source?: never;
  readonly onDisposeFailure?: never;
}

interface RuntimeProviderSourceProps<RuntimeServices = never, ER = never> extends RuntimeProviderChildren {
  readonly runtime?: never;
  /** Runtime source owned by this React provider and disposed with its component. */
  readonly source: ManagedRuntime.ManagedRuntime<RuntimeServices, ER> | Layer.Layer<RuntimeServices, ER, never>;
  /**
   * Observes failures from provider-owned runtime disposal.
   *
   * Promise-shaped observers are rejected by `EffectInput`; observer failures
   * are ignored after the disposal failure has been reported.
   */
  readonly onDisposeFailure?: (error: RuntimeDisposeError) => EffectInput<void>;
}

interface RuntimeProviderDefaultProps extends RuntimeProviderChildren {
  readonly runtime?: undefined;
  readonly source?: undefined;
  /**
   * Observes failures from provider-owned runtime disposal.
   *
   * Promise-shaped observers are rejected by `EffectInput`; observer failures
   * are ignored after the disposal failure has been reported.
   */
  readonly onDisposeFailure?: (error: RuntimeDisposeError) => EffectInput<void>;
}

/** Props accepted by React `RuntimeProvider` for host-owned or provider-owned runtimes. */
export type RuntimeProviderProps<RuntimeServices = never, ER = never> =
  | RuntimeProviderRuntimeProps<RuntimeServices, ER>
  | RuntimeProviderSourceProps<RuntimeServices, ER>
  | RuntimeProviderDefaultProps;

/** Creates an Effect UI runtime for React applications. */
export const createEffectRuntime = makeRuntime;

/** Reads the nearest React runtime context, falling back to the current/default runtime. */
export const useRuntime = <ER = never>(): AnyEffectUiRuntime<ER> =>
  (useContext(RuntimeContext) ?? currentOrDefaultRuntime()) as AnyEffectUiRuntime<ER>;

/**
 * Provides an Effect UI runtime to React children.
 *
 * Pass an existing runtime when the host owns lifecycle. Pass a runtime source
 * to let the provider create and dispose a runtime with the React component.
 */
export const RuntimeProvider = <RuntimeServices = never, ER = never>(
  props: RuntimeProviderProps<RuntimeServices, ER>
): ReactNode => {
  const ownedRuntimeRef = useRef<{
    readonly source: RuntimeProviderSourceProps<RuntimeServices, ER>["source"] | undefined;
    readonly runtime: AnyEffectUiRuntime<ER>;
  } | undefined>(undefined);
  const ownsRuntime = props.runtime === undefined;

  if (ownsRuntime) {
    const source = props.source;
    if (ownedRuntimeRef.current === undefined || ownedRuntimeRef.current.source !== source) {
      ownedRuntimeRef.current = {
        source,
        runtime: makeRuntime(source) as AnyEffectUiRuntime<ER>
      };
    }
  } else {
    ownedRuntimeRef.current = undefined;
  }

  const runtime = (props.runtime ?? ownedRuntimeRef.current?.runtime) as AnyEffectUiRuntime<ER>;
  const onDisposeFailureRef = useRef(props.onDisposeFailure);
  onDisposeFailureRef.current = props.onDisposeFailure;

  useEffect(() => {
    if (!ownsRuntime) {
      return undefined;
    }

    return () => {
      void Effect.runFork(
        runtime.disposeEffect.pipe(
          Effect.catch((error) =>
            onDisposeFailureRef.current === undefined
              ? Effect.void
              : invokeEffectInput("ReactRuntimeProvider.onDisposeFailure", onDisposeFailureRef.current, error).pipe(
                  Effect.catchCause(() => Effect.void),
                  Effect.asVoid
                )
          )
        )
      );
    };
  }, [ownsRuntime, runtime]);

  return createElement(RuntimeContext.Provider, {
    value: runtime as AnyEffectUiRuntime<never>,
    children: props.children
  });
};

/** Creates a `UiScope` bound to the current React component cleanup. */
export const useComponentScope = (): UiScope => {
  const runtime = useRuntime();
  const scopeRef = useRef<{
    readonly runtime: AnyEffectUiRuntime<unknown>;
    readonly frame: RuntimeUiScopeFrame<unknown>;
  } | undefined>(undefined);

  if (scopeRef.current === undefined || scopeRef.current.runtime !== runtime) {
    scopeRef.current = {
      runtime,
      frame: makeRuntimeUiScopeFrame(runtime)
    };
  }

  const frame = scopeRef.current.frame;

  useEffect(() => {
    return () => {
      void runtime.runFork(frame.disposeEffect());
    };
  }, [runtime, frame]);

  return frame.scope;
};

/** Runs synchronous construction while the component `UiScope` is ambient. */
export const useScoped = <A>(f: (scope: UiScope) => A): A => {
  const runtime = useRuntime();
  const scope = useComponentScope();
  return runWithRuntime(runtime, () => runWithScope(scope, () => f(scope)));
};
