// packages/solid-db/src/live-query.ts
import {
  collectionReactiveDepsValue,
  selectCollectionReactiveLiveQuery,
  type CollectionReactiveLiveQueryInput,
  type CollectionReactiveLiveQuerySelection,
  type LiveQuery,
  type LiveQueryState,
  type QueryEvaluationError,
} from "@sunfall/arc-db";
import type { EffectInput } from "@sunfall/arc-core";
import { useRuntime } from "@sunfall/arc-solid";
import { Effect } from "effect";
import { createMemo, type Accessor } from "solid-js";
import {
  liveQueryStateError,
  makeSolidDbReactiveBinding,
  type SolidDbReactiveBinding,
} from "./shared.js";

/** Options for Solid live-query hooks. */
export interface UseLiveQueryOptions<E = never, ER = never> {
  /** Solid dependencies that should rebuild the query when they change. */
  readonly deps?: (() => unknown) | undefined;
  /** Preload all query sources on mount. Defaults to true. */
  readonly preload?: boolean;
  /**
   * Observe failures from the automatic mount-time source preload.
   *
   * If this observer fails, the hook ignores that failure after updating
   * `preloadFailure`. Promise-shaped observers are rejected at the EffectInput
   * seam; adapt host Promise work explicitly with `Effect.tryPromise(...)`.
   */
  readonly onPreloadFailure?: (error: E | QueryEvaluationError | ER) => EffectInput<void, unknown>;
}

/**
 * Solid-facing handle for a live query over one or more collections.
 *
 * Data is recomputed when source collections change. Pass `deps` when the query
 * factory also reads Solid signals that should rebuild the query.
 */
export interface LiveQueryHandle<T, E = never, ER = never> {
  /** Current live query rows from the nearest Solid runtime. */
  readonly data: Accessor<ReadonlyArray<T>>;
  /** Current live query evaluation state, including source preload and query failures. */
  readonly state: Accessor<LiveQueryState<T, E | QueryEvaluationError>>;
  /** True while any query source is preloading or the query is refetching. */
  readonly waiting: Accessor<boolean>;
  /** Latest query evaluation or source preload failure, when the state is `Failure`. */
  readonly error: Accessor<E | QueryEvaluationError | undefined>;
  /** Failure captured from the automatic mount-time source preload, if enabled. */
  readonly preloadFailure: Accessor<E | QueryEvaluationError | ER | undefined>;
  /** Ensure all query sources have loaded inside the nearest Solid runtime. */
  preloadEffect(): Effect.Effect<void, E | QueryEvaluationError | ER>;
  /** Force a fresh source preload and live query evaluation inside the Solid runtime. */
  refetchEffect(): Effect.Effect<void, E | QueryEvaluationError | ER>;
}

type LiveQueryInput<T, E, R> = CollectionReactiveLiveQueryInput<T, E, R>;

/**
 * Subscribes a Solid component to a live query.
 *
 * Pass either a query factory or a prebuilt `LiveQuery`. The hook tracks all
 * source collections and recomputes `data` when they change.
 *
 * @example
 * ```tsx
 * const openProjects = useLiveQuery((query) =>
 *   query.from({ project: Projects })
 *     .where(({ project }) => project.status === "open")
 *     .select(({ project }) => project)
 * );
 * ```
 */
export const useLiveQuery = <T, E = never, R = never, ER = never>(
  input: LiveQueryInput<T, E, R>,
  options: UseLiveQueryOptions<E, ER> = {},
): LiveQueryHandle<T, E, ER> => {
  const runtime = useRuntime<ER>();
  let currentSelection: CollectionReactiveLiveQuerySelection<T, E, R, typeof runtime> | undefined;
  let binding: SolidDbReactiveBinding<E | QueryEvaluationError, ER> | undefined;
  const live = (): LiveQuery<T, E, R> => {
    const previous = currentSelection;
    currentSelection = selectCollectionReactiveLiveQuery(
      runtime,
      input,
      collectionReactiveDepsValue(options.deps),
      currentSelection,
    );
    if (currentSelection !== previous) {
      binding?.refreshSources();
    }
    return currentSelection.live;
  };
  binding = makeSolidDbReactiveBinding<E | QueryEvaluationError, R, ER>({
    runtime,
    sources: () => live().sources,
    preload: options.preload,
    preloadEffect: Effect.suspend(() => live().preloadEffect()),
    onPreloadFailure: options.onPreloadFailure,
  });

  const data = () => binding.read(() => live().data.get());

  const state = (): LiveQueryState<T, E | QueryEvaluationError> =>
    binding.read(() => live().state.get());

  return {
    data,
    state,
    waiting: createMemo(() => state().waiting),
    error: createMemo(() => liveQueryStateError(state())),
    preloadFailure: binding.preloadFailure,
    preloadEffect: () => binding.bindEffect(Effect.suspend(() => live().preloadEffect())),
    refetchEffect: () => binding.bindEffect(Effect.suspend(() => live().refetchEffect())),
  };
};

// packages/react-db/src/live-query.ts
import {
  collectionReactiveDepsValue,
  selectCollectionReactiveLiveQuery,
  type CollectionReactiveLiveQueryInput,
  type CollectionReactiveLiveQuerySelection,
  type LiveQueryState,
  type QueryEvaluationError,
} from "@sunfall/arc-db";
import type { EffectInput } from "@sunfall/arc-core";
import { useRuntime } from "@sunfall/arc-react";
import { Effect } from "effect";
import { useMemo, useRef } from "react";
import { liveQueryStateError, useReactDbReactiveBinding } from "./shared.js";

/** Options for React live-query hooks. */
export interface UseLiveQueryOptions<E = never, ER = never> {
  /** React dependencies that should rebuild the query when they change. */
  readonly deps?: ReadonlyArray<unknown> | (() => unknown);
  /** Preload all query sources on mount. Defaults to true. */
  readonly preload?: boolean;
  /**
   * Observe failures from the automatic mount-time source preload.
   *
   * If this observer fails, the hook ignores that failure after updating
   * `preloadFailure`. Promise-shaped observers are rejected at the EffectInput
   * seam; adapt host Promise work explicitly with `Effect.tryPromise(...)`.
   */
  readonly onPreloadFailure?: (error: E | QueryEvaluationError | ER) => EffectInput<void, unknown>;
}

/**
 * React-facing handle for a live query over one or more collections.
 *
 * Data is recomputed when source collections change. Pass `deps` when the query
 * factory also reads props/state that should rebuild the query.
 */
export interface LiveQueryHandle<T, E = never, ER = never> {
  /** Current live query rows from the nearest React runtime. */
  readonly data: ReadonlyArray<T>;
  /** Current live query evaluation state, including source preload and query failures. */
  readonly state: LiveQueryState<T, E | QueryEvaluationError>;
  /** True while any query source is preloading or the query is refetching. */
  readonly waiting: boolean;
  /** Latest query evaluation or source preload failure, when the state is `Failure`. */
  readonly error: E | QueryEvaluationError | undefined;
  /** Failure captured from the automatic mount-time source preload, if enabled. */
  readonly preloadFailure: E | QueryEvaluationError | ER | undefined;
  /** Ensure all query sources have loaded inside the nearest React runtime. */
  preloadEffect(): Effect.Effect<void, E | QueryEvaluationError | ER>;
  /** Force a fresh source preload and live query evaluation inside the React runtime. */
  refetchEffect(): Effect.Effect<void, E | QueryEvaluationError | ER>;
}

type LiveQueryInput<T, E, R> = CollectionReactiveLiveQueryInput<T, E, R>;

/**
 * Subscribes a React component to a live query.
 *
 * Pass either a query factory or a prebuilt `LiveQuery`. The hook tracks all
 * source collections and recomputes `data` when they change.
 */
export const useLiveQuery = <T, E = never, R = never, ER = never>(
  input: LiveQueryInput<T, E, R>,
  options: UseLiveQueryOptions<E, ER> = {},
): LiveQueryHandle<T, E, ER> => {
  const runtime = useRuntime<ER>();
  const inputRef = useRef(input);
  inputRef.current = input;
  const deps = collectionReactiveDepsValue(options.deps);
  const liveRef = useRef<CollectionReactiveLiveQuerySelection<T, E, R, typeof runtime> | undefined>(
    undefined,
  );
  liveRef.current = selectCollectionReactiveLiveQuery(
    runtime,
    inputRef.current,
    deps,
    liveRef.current,
  );
  const live = liveRef.current.live;
  const preloadEffect = useMemo(() => Effect.suspend(() => live.preloadEffect()), [live]);
  const binding = useReactDbReactiveBinding<E | QueryEvaluationError, R, ER>({
    runtime,
    sources: () => live.sources,
    preload: options.preload,
    preloadEffect,
    onPreloadFailure: options.onPreloadFailure,
  });

  const data = binding.read(() => live.data.get());
  const state = binding.read(() => live.state.get());

  return {
    data,
    state,
    waiting: state.waiting,
    error: liveQueryStateError(state),
    preloadFailure: binding.preloadFailure,
    preloadEffect: () => binding.bindEffect(Effect.suspend(() => live.preloadEffect())),
    refetchEffect: () => binding.bindEffect(Effect.suspend(() => live.refetchEffect())),
  };
};
